name: Activity 1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Environment
    - uses: actions/go-setup@v2
      with:
        go-version: '1.18'

    



