name: Activity 1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Environment
    - uses: actions/checkout@v2.4.0
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - run: |
        go version 
        ls
