name: Activity 1

on:
  push:
    branches: [main]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: 
    - name: Setup Go Environment
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Checking Go version
    - runs: go version
